// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUtgTNznYimkC8UcJ-A9YSLrtaeb63ncY',
    appId: '1:720868113659:web:5da8b09c97875422be445e',
    messagingSenderId: '720868113659',
    projectId: 'red2green-9066c',
    authDomain: 'red2green-9066c.firebaseapp.com',
    storageBucket: 'red2green-9066c.firebasestorage.app',
    measurementId: 'G-3HGQ966M0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC0SW0yYllpAe65CLpZLjQ9q9E3YRNEcE',
    appId: '1:720868113659:android:ed430d91840a180abe445e',
    messagingSenderId: '720868113659',
    projectId: 'red2green-9066c',
    storageBucket: 'red2green-9066c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGskS8bfmzUz3H1Q5_di7arFph1ByaZtU',
    appId: '1:720868113659:ios:b4ecfebe0914f575be445e',
    messagingSenderId: '720868113659',
    projectId: 'red2green-9066c',
    storageBucket: 'red2green-9066c.firebasestorage.app',
    iosBundleId: 'com.example.red2green',
  );
}